# Default state for all rules
default: true

# Line length
MD013: false  # Line length

# Allow multiple headers with the same content
MD024:
  allow_different_nesting: true

# Allow multiple top-level headers
MD025:
  level: 2

# Allow trailing punctuation in headers
MD026: false

# Allow bare URLs
MD034: false

# First line in file should be a top level header
MD041: false

# Allow multiple consecutive blank lines
MD012: false

# Allow inline HTML
MD033: false

# Allow duplicate headers
MD024: false

# Allow trailing spaces in code blocks
MD009: false

# Allow spaces after list markers
MD030: false

# Allow multiple spaces after list markers
MD007: false

# Allow unordered list style
MD004: false

# Allow ordered list item prefix
MD029: false

# Allow multiple spaces after ATX-style headers
MD018: false

# Allow spaces inside emphasis markers
MD037: false

# Allow bare URLs in link text
MD042: false

# Allow code blocks without language
MD040: false

# Allow code blocks without language
MD046: false

# Allow multiple top-level headers
MD002: false

# Allow trailing spaces in code blocks
MD009: false

# Allow multiple spaces after list markers
MD007: false

# Allow multiple spaces after ATX-style headers
MD018: false

# Allow spaces inside emphasis markers
MD037: false

# Allow bare URLs in link text
MD042: false

# Allow code blocks without language
MD040: false

# Allow code blocks without language
MD046: false

# Allow multiple top-level headers
MD002: false
