# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  # Python hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files  # Prevent giant files
        args: ['--maxkb=1024']
      - id: check-ast                # Check that files parse as valid Python
      - id: check-docstring-first    # Check for docstrings in Python files
      - id: check-json              # Check JSON files for parse errors
      - id: check-toml              # Check TOML files for parse errors
      - id: check-yaml              # Check YAML files for parse errors
      - id: debug-statements        # Check for debugger imports and breakpoints
      - id: end-of-file-fixer       # Ensure files end with a newline
      - id: mixed-line-ending       # Ensure consistent line endings
        args: ['--fix=lf']
      - id: trailing-whitespace     # Trim trailing whitespace
      - id: requirements-txt-fixer  # Sort requirements.txt
      - id: check-merge-conflict    # Check for merge conflict markers

  # Python formatting and linting
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=88]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
        args: [--profile=black, --filter-files]

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies: [
            'flake8-bugbear',
            'flake8-comprehensions',
            'flake8-docstrings',
            'darglint',
        ]
        args: [
            '--max-line-length=88',
            '--extend-ignore=E203,W503',  # Conflicts with Black
            '--per-file-ignores=__init__.py:F401',  # Allow unused imports in __init__.py
        ]

  # Type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies: [types-requests, types-pyyaml, types-python-dateutil]
        args: [--strict, --ignore-missing-imports, --implicit-optional]
        exclude: '^tests/'

  # Markdown linting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
        args: [--config=.markdownlint.yaml]
        additional_dependencies: ['markdownlint-cli2']

  # YAML linting
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.33.0
    hooks:
      - id: yamllint
        args: [--strict, --format=parsable, --config-file=.yamllint.yaml]

  # Rego (OPA) linting
  - repo: https://github.com/plexsystems/konstraint
    rev: v0.28.0
    hooks:
      - id: konstraint-validate
        name: Validate Rego policies
        entry: konstraint validate --skip-constraints
        language: golang
        types: [rego]
        files: \.rego$

  # Shell script linting
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck
        args: [--severity=warning]

  # Pre-commit hooks for Python project
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-no-log-warn
      - id: python-no-eval
      - id: python-use-type-annotations

  # Check for secrets in code
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: '^tests/'

  # Check for broken symlinks
  - repo: https://github.com/ecordell/pre-commit-hooks
    rev: v1.5.1
    hooks:
      - id: check-symlinks

  # Validate GitHub Actions workflows
  - repo: https://github.com/compilerla/action-validator
    rev: v1.0.1
    hooks:
      - id: action-validator
        files: '^\.github/workflows/.*\.ya?ml$'

  # Check for broken links in markdown
  - repo: https://github.com/lycheeverse/lychee-action
    rev: v1.8.2
    hooks:
      - id: lychee
        args: [--no-progress, --format=detailed, --exclude-mail]
        exclude: '^CHANGELOG\.md$'
