---
# Default configuration for yamllint

# Use the default (built-in) schema
extends: default

# Adjust some default settings
rules:
  # Line length
  line-length:
    max: 120
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true

  # Indentation
  indentation:
    spaces: 2
    indent-sequences: consistent
    check-multi-line-strings: false

  # Trailing spaces
  trailing-spaces: enable

  # Empty lines
  empty-lines:
    max: 2
    max-start: 1
    max-end: 1

  # Comments
  comments:
    min-spaces-from-content: 1

  # Document start
  document-start: disable  # Allow documents without --- at the start

  # Document end
  document-end: disable  # Don't require ... at the end

  # Key ordering
  key-ordering: disable  # Don't enforce key ordering

  # Quoted strings
  quoted-strings:
    quote-type: any  # Allow single or double quotes
    required: false

  # Braces in flow style
  braces:
    max-spaces-inside: 1
    min-spaces-inside: 0
    max-spaces-inside-empty: -1
    min-spaces-inside-empty: -1

  # Brackets in flow style
  brackets:
    max-spaces-inside: 1
    min-spaces-inside: 0
    max-spaces-inside-empty: -1
    min-spaces-inside-empty: -1

  # Commas in flow style
  commas:
    max-spaces-before: 0
    min-spaces-after: 1
    max-spaces-after: 1

  # Colons in flow style
  colons:
    max-spaces-before: 0
    max-spaces-after: 1

  # Hyphens in block sequences
  hyphens:
    max-spaces-after: 1

  # Indentation of sequence values
  indentation:
    spaces: 2
    indent-sequences: consistent
    check-multi-line-strings: false

  # Trailing spaces
  trailing-spaces: enable

  # Truthy values
  truthy:
    allowed-values: ['true', 'false', 'True', 'False', 'TRUE', 'FALSE', '~', 'null', 'Null', 'NULL', '']
    check-keys: false

# Exclude files and directories
exclude: |
  # Exclude common directories
  ^.git/
  ^.github/
  ^.idea/
  ^.vscode/
  ^__pycache__/
  ^.pytest_cache/
  ^.mypy_cache/
  ^.tox/
  ^venv/
  ^.venv/
  ^env/
  ^node_modules/
  ^dist/
  ^build/
  
  # Exclude common files
  ^.*\.min\.(js|css)$
  ^.*\.(md|markdown|txt|log|lock|json|sql|pyc|pyo|pyd|so|dll|exe|zip|tar\.gz|whl|egg|pth|o|a|lib|dylib)$
  ^.*~$
  ^\.DS_Store$
  ^\.gitignore$
  ^\.gitattributes$
  ^\.editorconfig$
  ^\.pre-commit-config\.yaml$
  ^\.yamllint\.yaml$
  ^\.markdownlint\.yaml$
