version: '3.8'

services:
  app:
    build: .
    container_name: governant-app
    volumes:
      - .:/app
      - /app/__pycache__
      - /app/.pytest_cache
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    command: bash
    stdin_open: true
    tty: true
    profiles:
      - dev

  test:
    build:
      context: .
      target: development
    container_name: governant-test
    volumes:
      - .:/app
      - /app/__pycache__
      - /app/.pytest_cache
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      bash -c "pytest -v --cov=src --cov-report=term-missing"
    profiles:
      - test

  lint:
    build:
      context: .
      target: development
    container_name: governant-lint
    volumes:
      - .:/app
    working_dir: /app
    command: >
      bash -c "black --check src/ tests/ && \
               isort --check-only src/ tests/ && \
               flake8 src/ tests/ && \
               mypy src/"
    profiles:
      - lint

networks:
  default:
    name: opa-policy-network
