name: Docker image smoke test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ development ]

permissions: {}

jobs:
  build-and-smoke:
    name: Build Docker image and run smoke checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU and Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build --progress=plain -t governant:ci -f docker/Dockerfile .

      - name: Show created images (debug)
        run: docker images | grep governant || true

      - name: Smoke test — CLI version
        run: |
          docker run --rm governant:ci --version || true

      - name: Smoke test — allow with bundled policy
        run: |
          # Mount test input as /input.json and run default CMD (allow against /input.json)
          docker run --rm -v ${{ github.workspace }}/test-inputs/production-valid.json:/input.json:ro governant:ci
