name: OPA Policy Evaluation

on:
  push:
    branches:
      - main

jobs:
  evaluate-policy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up uv (official)
        uses: astral-sh/setup-uv@v3
        with:
          version: 'latest'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'uv'

      - name: Set up OPA (official)
        uses: open-policy-agent/setup-opa@v3
        with:
          version: latest

      - name: Make scripts executable
        run: chmod +x scripts/*.sh

      - name: Compile policy to .compile/
        run: ./scripts/compile_policy.sh
        working-directory: ${{ github.workspace }}

      - name: Run OPA Policy Evaluation (OPA CLI)
        run: python -m src.opawasm .compile/github-release.tar.gz test-inputs/production-valid.json --prefer opa --entrypoint data.github.deploy.allow --format pretty
