name: Run Scripts

on:
  push:
    branches: [ main, development ]
    paths:
      - 'scripts/**'
      - '.github/workflows/scripts.yml'
  pull_request:
    branches: [ main, development ]
    paths:
      - 'scripts/**'
      - '.github/workflows/scripts.yml'
  workflow_dispatch:  # Allow manual triggering

jobs:
  run-scripts:
    name: Run Scripts
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install opa==0.51.0 jq
          sudo apt-get update && sudo apt-get install -y jq
          
      - name: Make scripts executable
        run: chmod +x scripts/*.sh
        
      - name: Run validate_schema.sh
        run: ./scripts/validate_schema.sh
        working-directory: ${{ github.workspace }}
        continue-on-error: false
        
      - name: Run validate_rego.sh
        run: ./scripts/validate_rego.sh
        working-directory: ${{ github.workspace }}
        continue-on-error: false
        
      - name: Run compile_policy.sh
        run: ./scripts/compile_policy.sh
        working-directory: ${{ github.workspace }}
        continue-on-error: false
        
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: policy-artifacts
          path: |
            compile/**
            .gate/*.json
          retention-days: 5
