name: Validate PR Policy

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  pull-requests: read
  contents: read
  checks: write

jobs:
  validate-pr-policy:
    name: Validate PR Policy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Make scripts executable
        run: chmod +x scripts/*.sh

      - name: Set up OPA
        uses: open-policy-agent/setup-opa@v2
        with:
          version: latest
          
      - name: Validate PR with OPA
        id: validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get PR information
          PR_NUMBER=${{ github.event.pull_request.number }}
          
          # Get approvals count
          APPROVALS=$(gh api \
            -H "Accept: application/vnd.github.v3+json" \
            "/repos/${{ github.repository }}/pulls/$PR_NUMBER/reviews" | \
            jq 'map(select(.state == "APPROVED") | .user.login) | unique | length')
          
          # Get code owner approvals
          CODE_OWNER_APPROVALS=$(gh api \
            -H "Accept: application/vnd.github.v3+json" \
            "/repos/${{ github.repository }}/pulls/$PR_NUMBER/reviews" | \
            jq 'map(select(.state == "APPROVED" and .author_association == "OWNER") | .user.login) | unique | length')
          
          # Create OPA input
          cat > input.json <<EOF
          {
            "environment": "pr_validation",
            "ref": "${{ github.head_ref }}",
            "workflow_meta": {
              "ticket_refs": ["$(echo ${{ github.event.pull_request.title }} | grep -oE '[A-Z]+-[0-9]+' || echo '')"],
              "approvers": $APPROVALS,
              "code_owner_approvals": $CODE_OWNER_APPROVALS,
              "signed_off": false,
              "deployments_today": 0,
              "tests_passed": ${{ github.event.pull_request.merged || 'false' }}
            }
          }
          EOF
          
          # Run OPA validation with PR policy
          opa eval --format pretty \
            --data .gate/pull_request.rego \
            --input input.json \
            "data.policy.allow"
      
      - name: Create check run
        if: always()
        uses: actions/github-script@v6
        with:
          script: |
            const { data } = await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'PR Policy Validation',
              head_sha: context.payload.pull_request.head.sha,
              status: 'completed',
              conclusion: steps.validate.outcome == 'success' ? 'success' : 'failure',
              output: {
                title: 'PR Policy Validation',
                summary: steps.validate.outcome == 'success' 
                  ? 'All PR policy checks passed' 
                  : 'PR policy validation failed',
                text: steps.validate.outcome == 'success' 
                  ? '✓ All PR policy requirements are met' 
                  : '✗ Some PR policy requirements are not met. Please check the PR details.'
              }
            })